# Generated by Django 3.2.9 on 2021-11-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last_name')),
                ('email', models.CharField(max_length=250, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_creat')),
                ('access_to_data', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
