# Generated by Django 3.2.9 on 2021-12-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dig_marketplace', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
