# Generated by Django 3.2.9 on 2021-12-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig_marketplace', '0005_customuser_month_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='day_joined',
            field=models.IntegerField(blank=True, default=0, verbose_name='day_joined'),
        ),
    ]
