# Generated by Django 3.2.9 on 2021-12-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig_marketplace', '0007_customuser_year_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_hash',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='email_hash'),
        ),
    ]
